spring:
  application:
    name: keyclaok-service
  datasource:
    url: jdbc:postgresql://172.21.0.3:5432/keycloak
    username: vikash
    password: vikash
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL81Dialect
      hibernate:
        ddl-auto: update
server:
  port: 9899

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG

keycloak:
  resource: customer-service
  realm: customer-realm
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  ssl-required: none
  credentials:
    secret: pf0BKpcWitYoLvokwpteoD5AYFp1PwIs
  use-resource-role-mappings: true
  bearer-only: true